export const RESET_ERROR_DATA = 'RESET_ERROR_DATA';
//基本資料設定
export const SET_BASE_DATA = 'SET_BASE_DATA';
export const MEMBER_DATA_REQUEST = 'MEMBER_DATA_REQUEST';
export const SET_MEMBER_DATA = 'SET_MEMBER_DATA';
export const MEMBER_DATA_FAIL = 'MEMBER_DATA_FAIL';
//目標載入
export const GOALS_DATA_REQUEST = 'GOALS_DATA_REQUEST';
export const SET_GOALS_DATA = 'SET_GOALS_DATA';
export const GOALS_DATA_FAIL = 'GOALS_DATA_FAIL';
//單一目標載入
export const GOAL_DATA_REQUEST = 'GOAL_DATA_REQUEST';
export const SET_GOAL_DATA = 'SET_GOAL_DATA';
export const GOAL_DATA_FAIL = 'GOAL_DATA_FAIL';
//編輯目標
export const EDIT_GOAL_REQUEST = 'EDIT_GOAL_REQUEST';
export const EDIT_GOAL_DATA = 'EDIT_GOAL_DATA';
export const EDIT_GOAL_FAIL = 'EDIT_GOAL_FAIL';
//刪除目標
export const DELETE_GOAL_REQUEST = 'DELETE_GOAL_REQUEST';
export const DELETE_GOAL_DATA = 'DELETE_GOAL_DATA';
export const DELETE_GOAL_FAIL = 'DELETE_GOAL_FAIL';
//規劃進度
export const PLAN_GOAL_REQUEST = 'PLAN_GOAL_REQUEST';
export const PLAN_GOAL_DATA = 'PLAN_GOAL_DATA';
export const PLAN_GOAL_FAIL = 'PLAN_GOAL_FAIL';
//更新進度
export const UPDATE_GOAL_REQUEST = 'UPDATE_GOAL_REQUEST';
export const UPDATE_GOAL_DATA = 'UPDATE_GOAL_DATA';
export const UPDATE_GOAL_FAIL = 'UPDATE_GOAL_FAIL';
//獎勵載入
export const PRIZES_DATA_REQUEST ='PRIZES_DATA_REQUEST';
export const SET_PRIZES_DATA = 'SET_PRIZES_DATA';
export const PRIZES_DATA_FAIL = 'PRIZES_DATA_FAIL';
//刪除獎勵
export const DELETE_PRIZE_REQUEST = 'DELETE_PRIZE_REQUEST';
export const DELETE_PRIZE_DATA = 'DELETE_PRIZE_DATA';
export const DELETE_PRIZE_FAIL = 'DELETE_PRIZE_FAIL';
//新增獎勵
export const ADD_PRIZE_REQUEST = 'ADD_PRIZE_REQUEST';
export const ADD_PRIZE_DATA = 'ADD_PRIZE_DATA';
export const ADD_PRIZE_FAIL = 'ADD_PRIZE_FAIL';
//單一目標載入
export const PRIZE_DATA_REQUEST = 'PRIZE_DATA_REQUEST';
export const SET_PRIZE_DATA = 'SET_PRIZE_DATA';
export const PRIZE_DATA_FAIL = 'PRIZE_DATA_FAIL';
//編輯獎勵
export const EDIT_PRIZE_REQUEST = 'EDIT_PRIZE_REQUEST';
export const EDIT_PRIZE_DATA = 'EDIT_PRIZE_DATA';
export const EDIT_PRIZE_FAIL = 'EDIT_PRIZE_FAIL';
//分享卡載入
export const CARDS_DATA_REQUEST ='CARDS_DATA_REQUEST';
export const SET_CARDS_DATA = 'SET_CARDS_DATA';
export const CARDS_DATA_FAIL = 'CARDS_DATA_FAIL';
//單一分享卡載入
export const CARD_DATA_REQUEST = 'CARD_DATA_REQUEST';
export const SET_CARD_DATA = 'SET_CARD_DATA';
export const CARD_DATA_FAIL = 'CARD_DATA_FAIL';
//刪除分享卡
export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';
export const DELETE_CARD_DATA = 'DELETE_CARD_DATA';
export const DELETE_CARD_FAIL = 'DELETE_CARD_FAIL';
//編輯目標
export const EDIT_CARD_REQUEST = 'EDIT_CARD_REQUEST';
export const EDIT_CARD_DATA = 'EDIT_CARD_DATA';
export const EDIT_CARD_FAIL = 'EDIT_CARD_FAIL';